services:
  api:
    container_name: life-planner-back
    build: .
    ports:
      - '1009:3000'
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:3000/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
